export const txt = {
  // index.tsx
  choose_network: "Choose Network:",
  choose_protocol: "Choose Protocol:",
  required_error: "This field is required",
  sell: "Sell",
  receive: "Receive",
  max: "Max",
  half: "Half",
  in_wallet: "In wallet:",
  how_much: " How much ",
  do_you_want_to_invest: "do you want to invest?",
  executes: "Executes",
  how_many_day: "How many days?",
  woohoo: "Woohoo! All steps completed! 🎉",
  start_over: "Start Over",
  finish: "Finish",
  continue: "Continue",
  go_back: "Go Back",
  you_will_invest: "You'll Invest",
  we_will_swap: "We'll Swap",
  everyday_for: "Everyday for",
  days: "days",
  create_position: "Create Position",
  defiWrap: "DefiWrap",
  defiLlama: "DefiLlama",

  //   searchModal.tsx
  select: "Select",
  token_list: " Token List",
  cancel: "Cancel",
  you_pay: "You Pay",
};
